{
    "data": [
        {
            "categoryId": 0,
            "categoryName": "",
            "icon": "",
            "sort": 0,
            "list": [
                {
                    "id": 21,
                    "sysLanguage": "en",
                    "activityType": 0,
                    "informationType": 2,
                    "title": "vip center -english",
                    "imgUrl": "/img/6006/vendorlogo/081757466-39122-file_20260512081757050.webp",
                    "state": 1,
                    "sort": 70,
                    "displayTarget": 1,
                    "displayDetail": "{\"Group\":\"1000001,1000002\"}",
                    "content": "",
                    "pageType": 7,
                    "pageId": 0,
                    "startTime": 1778409262296,
                    "creator": "Jayadmin",
                    "createTime": 1775215884846,
                    "lastUpdateMan": "admin00",
                    "lastUpdateTime": 1778573880027,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": {
                        "userVipLevel": 0,
                        "totalUserCanReceiveAmount": 0.00,
                        "canReceiveLevelAmount": 0.0,
                        "canReceiveWeekAmount": 0.00,
                        "canReceiveMonthAmount": 0.00,
                        "currentRechargeAmount": 300.0000,
                        "targetRechargeAmount": 2000.00,
                        "currentBetAmount": 1486.3400,
                        "targetBetAmount": 6000.00
                    },
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "",
                    "gameCode": "",
                    "gameId": 0
                },
                {
                    "id": 29,
                    "sysLanguage": "en",
                    "activityType": 0,
                    "informationType": 2,
                    "title": "superjackpot-english",
                    "imgUrl": "/img/6006/vendorlogo/024134357-36958-file_20260507144134344.webp",
                    "state": 1,
                    "sort": 5,
                    "displayTarget": 1,
                    "displayDetail": "{\"Group\":\"1000001,1000002,1000003\"}",
                    "content": "",
                    "pageType": 5,
                    "pageId": 0,
                    "startTime": 1778164984584,
                    "creator": "System",
                    "createTime": 1775740182774,
                    "lastUpdateMan": "admin00",
                    "lastUpdateTime": 1778164984584,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": {
                        "totalRewardAmount": 0.0,
                        "records": []
                    },
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "",
                    "gameCode": "",
                    "gameId": 0
                },
                {
                    "id": 17,
                    "sysLanguage": "en",
                    "activityType": 0,
                    "informationType": 2,
                    "title": "rechargespin-english",
                    "imgUrl": "/img/6006/vendorlogo/020852658-36370-file_20260506140852640.webp",
                    "state": 1,
                    "sort": 60,
                    "displayTarget": 1,
                    "displayDetail": "{\"Group\":\"1000001,1000002\"}",
                    "content": "",
                    "pageType": 14,
                    "pageId": 0,
                    "startTime": 1778076509736,
                    "creator": "Jayadmin",
                    "createTime": 1775215884846,
                    "lastUpdateMan": "admin00",
                    "lastUpdateTime": 1778076554020,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": {
                        "remainSpinCount": 0,
                        "silverWheelTimes": 0,
                        "goldWheelTimes": 0,
                        "diamondWheelTimes": 0,
                        "specialWheelTimes": 0,
                        "currentRechargeAmount": 300.0000,
                        "targetRechargeAmount": 500.0
                    },
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "",
                    "gameCode": "",
                    "gameId": 0
                },
                {
                    "id": 27,
                    "sysLanguage": "en",
                    "activityType": 0,
                    "informationType": 2,
                    "title": "dailytasks-english",
                    "imgUrl": "/img/6006/vendorlogo/055152485-33594-file_20260428055152467.webp",
                    "state": 1,
                    "sort": 40,
                    "displayTarget": 1,
                    "displayDetail": "{\"Group\":\"1000001,1000002\"}",
                    "content": "",
                    "pageType": 19,
                    "pageId": 0,
                    "startTime": 1777205429724,
                    "creator": "Jayadmin",
                    "createTime": 1775215884846,
                    "lastUpdateMan": "admin00",
                    "lastUpdateTime": 1778057986778,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": {
                        "totalCanReceiveAmount": 0.0,
                        "totalCanReceiveExp": 0,
                        "pendingDayTask": [
                            {
                                "id": 52,
                                "taskLogo": "/img/6006/other/100621371-33671-file_20260428100621369.webp",
                                "taskTitle": "GO! WniGo(30s)",
                                "taskType": 0,
                                "taskDetailType": 3,
                                "needRechargeAmount": 0.0000,
                                "minVipLevel": 0,
                                "taskDetail": {
                                    "rechargeAmount": 100.0,
                                    "betAmount": 350.0,
                                    "betCount": 0,
                                    "minSingleBetAmount": 0.0,
                                    "vendorCode": "ARLottery",
                                    "vendorName": "AR",
                                    "categoryCode": "",
                                    "categoryType": 3,
                                    "gameCode": [
                                        "WinGo_30S"
                                    ],
                                    "gameName": [
                                        "WinGo 30sec"
                                    ],
                                    "gameIds": [
                                        10005
                                    ],
                                    "invitedUserCount": 0
                                },
                                "currentTaskDetail": {
                                    "rechargeAmount": 0.0000,
                                    "betAmount": 0.0,
                                    "betCount": 0,
                                    "minSingleBetAmount": 0.0,
                                    "vendorCode": null,
                                    "vendorName": null,
                                    "categoryCode": null,
                                    "categoryType": null,
                                    "gameCode": null,
                                    "gameName": null,
                                    "gameIds": null,
                                    "invitedUserCount": 0
                                },
                                "mainRewardType": 0,
                                "rewardDetail": null,
                                "rewardAmount": 2.0000,
                                "codingMultiple": 1.0000,
                                "experienceScore": 2,
                                "endDate": "2027-04-28 00:00:00",
                                "sort": 889,
                                "dayWeekStatus": 0
                            }
                        ],
                        "pendingWeekTask": [
                            {
                                "id": 57,
                                "taskLogo": "3",
                                "taskTitle": "Top-up NOW! ",
                                "taskType": 1,
                                "taskDetailType": 0,
                                "needRechargeAmount": 0.0000,
                                "minVipLevel": 0,
                                "taskDetail": {
                                    "rechargeAmount": 100000.0,
                                    "betAmount": 0.0,
                                    "betCount": 0,
                                    "minSingleBetAmount": 0.0,
                                    "vendorCode": null,
                                    "vendorName": null,
                                    "categoryCode": null,
                                    "categoryType": null,
                                    "gameCode": [],
                                    "gameName": null,
                                    "gameIds": null,
                                    "invitedUserCount": 0
                                },
                                "currentTaskDetail": {
                                    "rechargeAmount": 0.0000,
                                    "betAmount": 0.0,
                                    "betCount": 0,
                                    "minSingleBetAmount": 0.0,
                                    "vendorCode": null,
                                    "vendorName": null,
                                    "categoryCode": null,
                                    "categoryType": null,
                                    "gameCode": null,
                                    "gameName": null,
                                    "gameIds": null,
                                    "invitedUserCount": 0
                                },
                                "mainRewardType": 0,
                                "rewardDetail": null,
                                "rewardAmount": 117.0000,
                                "codingMultiple": 1.0000,
                                "experienceScore": 10,
                                "endDate": "2027-04-28 00:00:00",
                                "sort": 999,
                                "dayWeekStatus": 0
                            }
                        ]
                    },
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "",
                    "gameCode": "",
                    "gameId": 0
                },
                {
                    "id": 26,
                    "sysLanguage": "en",
                    "activityType": 0,
                    "informationType": 2,
                    "title": "bet rebate-english",
                    "imgUrl": "/img/6006/vendorlogo/094557589-33269-file_20260426094557571.webp",
                    "state": 1,
                    "sort": 20,
                    "displayTarget": 1,
                    "displayDetail": "{\"Group\":\"1000001,1000002\"}",
                    "content": "",
                    "pageType": 6,
                    "pageId": 0,
                    "startTime": 1777196834254,
                    "creator": "Jayadmin",
                    "createTime": 1775215884846,
                    "lastUpdateMan": "admin00",
                    "lastUpdateTime": 1778058012123,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": {
                        "pendingWashCodeAmount": 0.00,
                        "isOpenCodeWashing": true,
                        "isFrontManualCodeWashing": true,
                        "isSettleTheWashingAmount": true
                    },
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "",
                    "gameCode": "",
                    "gameId": 0
                },
                {
                    "id": 28,
                    "sysLanguage": "en",
                    "activityType": 0,
                    "informationType": 2,
                    "title": "daily checkin-eng",
                    "imgUrl": "/img/6006/vendorlogo/094621860-33270-file_20260426094621844.webp",
                    "state": 1,
                    "sort": 10,
                    "displayTarget": 1,
                    "displayDetail": "{\"Group\":\"1000001,1000002\"}",
                    "content": "",
                    "pageType": 20,
                    "pageId": 0,
                    "startTime": 1777196826496,
                    "creator": "Jayadmin",
                    "createTime": 1775215884846,
                    "lastUpdateMan": "admin00",
                    "lastUpdateTime": 1778058026670,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": {
                        "activityId": 28,
                        "activityName": "checkin-vip0",
                        "statisticsType": 0,
                        "activityType": 1,
                        "status": 1,
                        "rewardDetail": {
                            "status": 1,
                            "dayIndex": 1,
                            "rechargeAmount": 100.0,
                            "rewardType": 0,
                            "rewardAmount": 1.0
                        },
                        "rechargeAmount": 0.0000,
                        "currentCheckInDays": 1
                    },
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "",
                    "gameCode": "",
                    "gameId": 0
                },
                {
                    "id": 15,
                    "sysLanguage": "en",
                    "activityType": 0,
                    "informationType": 2,
                    "title": "GiftCodes-eng",
                    "imgUrl": "/img/6006/vendorlogo/094518325-33268-file_20260426094518310.webp",
                    "state": 1,
                    "sort": 30,
                    "displayTarget": 1,
                    "displayDetail": "{\"Group\":\"1000001,1000002\"}",
                    "content": "",
                    "pageType": 3,
                    "pageId": 0,
                    "startTime": 1776877344916,
                    "creator": "Jayadmin",
                    "createTime": 1775215884846,
                    "lastUpdateMan": "admin00",
                    "lastUpdateTime": 1778057998938,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": null,
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "",
                    "gameCode": "",
                    "gameId": 0
                },
                {
                    "id": 200000001,
                    "sysLanguage": "en",
                    "activityType": 1,
                    "informationType": 6,
                    "title": "ARBET 2026",
                    "imgUrl": "/img/6006/vendorlogo/095120583-75322-file_20260710215120521.webp",
                    "state": 1,
                    "sort": 0,
                    "displayTarget": 1,
                    "displayDetail": "",
                    "content": "",
                    "pageType": 0,
                    "pageId": 0,
                    "startTime": 1783706665769,
                    "creator": "dhzuzhang09",
                    "createTime": 1783706665769,
                    "lastUpdateMan": "DHadmin",
                    "lastUpdateTime": 1783943517558,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": null,
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "ARBET",
                    "gameCode": "sr:sport:63",
                    "gameId": 25502
                },
                {
                    "id": 139360002,
                    "sysLanguage": "en",
                    "activityType": 1,
                    "informationType": 5,
                    "title": "shenmicaijin-hindi",
                    "imgUrl": "/img/6006/vendorlogo/083621588-40320-file_20260515083620824.webp",
                    "state": 1,
                    "sort": 997,
                    "displayTarget": 1,
                    "displayDetail": "{\"Group\":\"1000001,1000002\"}",
                    "content": "/activity",
                    "pageType": 0,
                    "pageId": 0,
                    "startTime": 1778834139371,
                    "creator": "admin00",
                    "createTime": 1778834139371,
                    "lastUpdateMan": "admin00",
                    "lastUpdateTime": 1779543777880,
                    "activityInquiryType": 0,
                    "rechargeAmount": 0.0,
                    "conditionIndex": 0,
                    "rechargeGiftPackId": 0,
                    "buyMode": 0,
                    "isShowTips": false,
                    "tipsDetail": null,
                    "newActivityState": 0,
                    "badge": 0,
                    "badgeCode": "",
                    "categoryIds": "",
                    "vendorCode": "",
                    "gameCode": "",
                    "gameId": 0
                }
            ]
        }
    ],
    "code": 0,
    "msg": "Succeed",
    "msgCode": 0,
    "serverTime": 1784362021715
}
